import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateAiLearningSystem1699999999999 implements MigrationInterface {
  name = 'CreateAiLearningSystem1699999999999';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // AI Interactions Table
    await queryRunner.query(`
      CREATE TABLE "ai_interactions" (
        "id" SERIAL NOT NULL,
        "userId" text NOT NULL,
        "userRole" text NOT NULL,
        "sessionId" text,
        "question" text NOT NULL,
        "sqlQuery" text,
        "response" text,
        "responseTimeMs" integer,
        "context" jsonb,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        PRIMARY KEY ("id")
      )
    `);

    // AI Feedback Table
    await queryRunner.query(`
      CREATE TABLE "ai_feedback" (
        "id" SERIAL NOT NULL,
        "interactionId" integer NOT NULL,
        "feedbackType" text NOT NULL,
        "rating" integer,
        "accuracyRating" integer,
        "usefulnessRating" integer,
        "clarityRating" integer,
        "feedbackComment" text,
        "whatWasGood" text,
        "whatCouldBeBetter" text,
        "additionalContext" text,
        "didUserFollowUp" boolean NOT NULL DEFAULT false,
        "didUserModifyQuery" boolean NOT NULL DEFAULT false,
        "timeSpentOnResponse" integer,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        PRIMARY KEY ("id")
      )
    `);

    // AI Patterns Table
    await queryRunner.query(`
      CREATE TABLE "ai_patterns" (
        "id" SERIAL NOT NULL,
        "patternType" text NOT NULL,
        "pattern" text NOT NULL,
        "category" text NOT NULL,
        "subcategory" text,
        "keywords" text array NOT NULL DEFAULT '{}',
        "frequency" integer NOT NULL DEFAULT 1,
        "successRate" numeric(3,2) NOT NULL DEFAULT 0.0,
        "confidenceScore" numeric(3,2) NOT NULL DEFAULT 0.0,
        "lastUsed" TIMESTAMP,
        "lastSuccess" TIMESTAMP,
        "autoGenerated" boolean NOT NULL DEFAULT false,
        "isActive" boolean NOT NULL DEFAULT true,
        "templateExample" text,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        PRIMARY KEY ("id")
      )
    `);

    // AI Prompt Templates Table
    await queryRunner.query(`
      CREATE TABLE "ai_prompt_templates" (
        "id" SERIAL NOT NULL,
        "templateName" text NOT NULL,
        "category" text NOT NULL,
        "subcategory" text,
        "templatePattern" text NOT NULL,
        "variables" text array NOT NULL DEFAULT '{}',
        "description" text,
        "successCount" integer NOT NULL DEFAULT 0,
        "usageCount" integer NOT NULL DEFAULT 0,
        "successRate" numeric(3,2) NOT NULL DEFAULT 0.0,
        "averageResponseTime" integer,
        "lastUsed" TIMESTAMP,
        "isActive" boolean NOT NULL DEFAULT true,
        "autoGenerated" boolean NOT NULL DEFAULT false,
        "version" integer NOT NULL DEFAULT 1,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        PRIMARY KEY ("id")
      )
    `);

    // AI Query Vectors Table - using simple array for now
    await queryRunner.query(`
      CREATE TABLE "ai_query_vectors" (
        "id" SERIAL NOT NULL,
        "interactionId" integer NOT NULL,
        "queryVector" numeric array,
        "category" text,
        "intent" text,
        "similarityScore" numeric(3,2),
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        PRIMARY KEY ("id")
      )
    `);

    // AI Learning Metrics Table
    await queryRunner.query(`
      CREATE TABLE "ai_learning_metrics" (
        "id" SERIAL NOT NULL,
        "metricDate" date NOT NULL,
        "totalInteractions" integer NOT NULL DEFAULT 0,
        "successfulInteractions" integer NOT NULL DEFAULT 0,
        "averageFeedbackScore" numeric(3,2),
        "newPatternsDiscovered" integer NOT NULL DEFAULT 0,
        "templatesGenerated" integer NOT NULL DEFAULT 0,
        "accuracyImprovement" numeric(3,2),
        "responseTimeImprovement" integer,
        "uniqueQueries" integer NOT NULL DEFAULT 0,
        "repeatQueries" integer NOT NULL DEFAULT 0,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
        PRIMARY KEY ("id"),
        UNIQUE ("metricDate")
      )
    `);

    // AI A/B Tests Table
    await queryRunner.query(`
      CREATE TABLE "ai_ab_tests" (
        "id" SERIAL NOT NULL,
        "testName" text NOT NULL,
        "description" text,
        "templateAId" integer,
        "templateBId" integer,
        "trafficSplit" numeric(3,2) NOT NULL DEFAULT 0.5,
        "impressionsA" integer NOT NULL DEFAULT 0,
        "impressionsB" integer NOT NULL DEFAULT 0,
        "conversionsA" integer NOT NULL DEFAULT 0,
        "conversionsB" integer NOT NULL DEFAULT 0,
        "successRateA" numeric(3,2),
        "successRateB" numeric(3,2),
        "statisticalSignificance" boolean NOT NULL DEFAULT false,
        "confidenceLevel" numeric(3,2),
        "winner" text,
        "status" text NOT NULL DEFAULT 'running',
        "startDate" TIMESTAMP NOT NULL DEFAULT now(),
        "endDate" TIMESTAMP,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        PRIMARY KEY ("id")
      )
    `);

    // AI Context Memory Table
    await queryRunner.query(`
      CREATE TABLE "ai_context_memory" (
        "id" SERIAL NOT NULL,
        "userId" text NOT NULL,
        "sessionId" text,
        "contextType" text NOT NULL,
        "contextData" jsonb NOT NULL,
        "expiresAt" TIMESTAMP,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        PRIMARY KEY ("id")
      )
    `);

    // Create indexes
    await queryRunner.query(`CREATE INDEX "idx_ai_interactions_user" ON "ai_interactions" ("userId")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_interactions_created" ON "ai_interactions" ("createdAt")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_feedback_interaction" ON "ai_feedback" ("interactionId")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_patterns_type" ON "ai_patterns" ("patternType")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_patterns_category" ON "ai_patterns" ("category")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_templates_category" ON "ai_prompt_templates" ("category")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_vectors_query" ON "ai_query_vectors" USING GIN ("queryVector")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_metrics_date" ON "ai_learning_metrics" ("metricDate")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_context_user" ON "ai_context_memory" ("userId")`);
    await queryRunner.query(`CREATE INDEX "idx_ai_context_session" ON "ai_context_memory" ("sessionId")`);

    // Create foreign key constraints
    await queryRunner.query(`
      ALTER TABLE "ai_feedback" 
      ADD CONSTRAINT "fk_ai_feedback_interaction" 
      FOREIGN KEY ("interactionId") REFERENCES "ai_interactions"("id") ON DELETE CASCADE
    `);

    await queryRunner.query(`
      ALTER TABLE "ai_query_vectors" 
      ADD CONSTRAINT "fk_ai_vectors_interaction" 
      FOREIGN KEY ("interactionId") REFERENCES "ai_interactions"("id") ON DELETE CASCADE
    `);

    // Create trigger function for updating timestamps
    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION update_updated_at_column()
      RETURNS TRIGGER AS $$
      BEGIN
          NEW."updatedAt" = NOW();
          RETURN NEW;
      END;
      $$ language 'plpgsql'
    `);

    // Create triggers
    await queryRunner.query(`
      CREATE TRIGGER "update_ai_interactions_updated_at" 
      BEFORE UPDATE ON "ai_interactions" 
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
    `);

    await queryRunner.query(`
      CREATE TRIGGER "update_ai_patterns_updated_at" 
      BEFORE UPDATE ON "ai_patterns" 
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
    `);

    await queryRunner.query(`
      CREATE TRIGGER "update_ai_templates_updated_at" 
      BEFORE UPDATE ON "ai_prompt_templates" 
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
    `);

    await queryRunner.query(`
      CREATE TRIGGER "update_ai_metrics_updated_at" 
      BEFORE UPDATE ON "ai_learning_metrics" 
      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop tables in reverse order
    await queryRunner.query(`DROP TABLE IF EXISTS "ai_context_memory"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ai_ab_tests"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ai_learning_metrics"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ai_query_vectors"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ai_prompt_templates"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ai_patterns"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ai_feedback"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "ai_interactions"`);
    
    // Drop trigger function
    await queryRunner.query(`DROP FUNCTION IF EXISTS update_updated_at_column`);
  }
}
