import { Repository, DataSource } from 'typeorm';
import { AiPromptTemplate } from '../entities/ai-prompt-template.entity';
import { AiPattern } from '../entities/ai-pattern.entity';

export class PromptManager {
  
  private templateCache = new Map<string, AiPromptTemplate[]>();

  private templateRepository: Repository<AiPromptTemplate>;
  private patternRepository: Repository<AiPattern>;

  constructor(dataSource: DataSource) {
    this.templateRepository = dataSource.getRepository(AiPromptTemplate);
    this.patternRepository = dataSource.getRepository(AiPattern);
    this.initializeDefaultTemplates();
  }

  async getBestTemplate(category: string, intent?: string): Promise<AiPromptTemplate> {
    // Check cache first
    const cacheKey = `${category}_${intent || 'default'}`;
    if (this.templateCache.has(cacheKey)) {
      const templates = this.templateCache.get(cacheKey)!;
      return this.selectBestTemplate(templates);
    }

    // Query database
    const templates = await this.templateRepository.find({
      where: {
        category,
        isActive: true,
      },
      order: {
        successRate: 'DESC',
        usageCount: 'DESC',
      },
    });

    // Cache the results
    this.templateCache.set(cacheKey, templates);

    return this.selectBestTemplate(templates);
  }

  async createTemplate(templateData: Partial<AiPromptTemplate>): Promise<AiPromptTemplate> {
    const template = await this.templateRepository.save(templateData);
    this.clearCache();
    return template;
  }

  async updateTemplate(id: number, updates: Partial<AiPromptTemplate>): Promise<AiPromptTemplate | null> {
    await this.templateRepository.update(id, updates);
    this.clearCache();
    return this.templateRepository.findOne({ where: { id } });
  }

  async getTemplatesByCategory(category?: string): Promise<AiPromptTemplate[]> {
    const where = category ? { category, isActive: true } : { isActive: true };
    return this.templateRepository.find({
      where,
      order: { category: 'ASC', subcategory: 'ASC' },
    });
  }

  private selectBestTemplate(templates: AiPromptTemplate[]): AiPromptTemplate {
    if (!templates || templates.length === 0) {
      return this.getDefaultTemplate();
    }

    // Use weighted scoring: success rate (70%) + usage count (30%)
    const maxUsage = Math.max(...templates.map(t => t.usageCount));
    
    return templates.reduce((best, current) => {
      const bestScore = (best.successRate * 0.7) + ((best.usageCount / maxUsage) * 0.3);
      const currentScore = (current.successRate * 0.7) + ((current.usageCount / maxUsage) * 0.3);
      
      return currentScore > bestScore ? current : best;
    });
  }

  private getDefaultTemplate(): AiPromptTemplate {
    return {
      id: 0,
      templateName: 'Default Template',
      category: 'default',
      templatePattern: 'Answer the following question: {question}',
      variables: ['question'],
      description: 'Default template for general queries',
      successCount: 0,
      usageCount: 0,
      successRate: 0,
      isActive: true,
      autoGenerated: false,
      version: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as AiPromptTemplate;
  }

  private clearCache(): void {
    this.templateCache.clear();
  }

  private async initializeDefaultTemplates(): Promise<void> {
    const existingCount = await this.templateRepository.count();
    if (existingCount > 0) return; // Already initialized

    const defaultTemplates = this.getDefaultTemplates();
    await this.templateRepository.save(defaultTemplates);
    console.log(`Initialized ${defaultTemplates.length} default prompt templates`);
  }

  private getDefaultTemplates(): Partial<AiPromptTemplate>[] {
    return [
      // Student Performance Templates
      {
        templateName: 'Individual Student Performance',
        category: 'academic_performance',
        subcategory: 'individual',
        templatePattern: 'Show me how {student_name} is performing in {subject}',
        variables: ['student_name', 'subject'],
        description: 'Get individual student performance in a specific subject',
      },
      {
        templateName: 'Student Progress Over Time',
        category: 'academic_performance',
        subcategory: 'individual',
        templatePattern: 'Show {student_name}\'s progress over the last {timeframe}',
        variables: ['student_name', 'timeframe'],
        description: 'Track student progress over a time period',
      },
      {
        templateName: 'Class Performance Overview',
        category: 'academic_performance',
        subcategory: 'class',
        templatePattern: 'Show the overall performance of class {class_name}',
        variables: ['class_name'],
        description: 'Get class-wise performance overview',
      },
      {
        templateName: 'Class Comparison',
        category: 'academic_performance',
        subcategory: 'comparative',
        templatePattern: 'Compare the performance of {class1} and {class2} in {subject}',
        variables: ['class1', 'class2', 'subject'],
        description: 'Compare performance between two classes',
      },
      {
        templateName: 'Subject Performance Analysis',
        category: 'academic_performance',
        subcategory: 'subject',
        templatePattern: 'How are students performing in {subject} across all classes?',
        variables: ['subject'],
        description: 'Analyze subject performance across classes',
      },
      {
        templateName: 'Struggling Students Identification',
        category: 'academic_performance',
        subcategory: 'individual',
        templatePattern: 'Which students in {class_name} are struggling in {subject}?',
        variables: ['class_name', 'subject'],
        description: 'Identify students who need help',
      },
      {
        templateName: 'Top Performers',
        category: 'academic_performance',
        subcategory: 'individual',
        templatePattern: 'Who are the top performing students in {subject}?',
        variables: ['subject'],
        description: 'Get list of top performers',
      },
      {
        templateName: 'Performance Trend Analysis',
        category: 'academic_performance',
        subcategory: 'trend',
        templatePattern: 'What is the trend of {metric} for {entity} over {timeframe}?',
        variables: ['metric', 'entity', 'timeframe'],
        description: 'Analyze performance trends',
      },

      // Financial Management Templates
      {
        templateName: 'Fee Collection Status',
        category: 'financial_management',
        subcategory: 'fee_analysis',
        templatePattern: 'Show the fee collection status for {month}',
        variables: ['month'],
        description: 'Get fee collection report for a month',
      },
      {
        templateName: 'Pending Fees List',
        category: 'financial_management',
        subcategory: 'fee_analysis',
        templatePattern: 'Which students have pending fees for {month}?',
        variables: ['month'],
        description: 'Get list of students with pending fees',
      },
      {
        templateName: 'Monthly Revenue Report',
        category: 'financial_management',
        subcategory: 'revenue_analysis',
        templatePattern: 'What is the total revenue for {month}?',
        variables: ['month'],
        description: 'Get total revenue for a month',
      },
      {
        templateName: 'Revenue Comparison',
        category: 'financial_management',
        subcategory: 'revenue_analysis',
        templatePattern: 'Compare revenue between {month1} and {month2}',
        variables: ['month1', 'month2'],
        description: 'Compare revenue between two months',
      },
      {
        templateName: 'Fee Payment Patterns',
        category: 'financial_management',
        subcategory: 'fee_analysis',
        templatePattern: 'What are the common payment patterns for fees?',
        variables: [],
        description: 'Analyze fee payment patterns',
      },
      {
        templateName: 'Teacher Payouts',
        category: 'financial_management',
        subcategory: 'expense_tracking',
        templatePattern: 'Show teacher payouts for {month}',
        variables: ['month'],
        description: 'Get teacher payout report',
      },
      {
        templateName: 'Course-wise Revenue',
        category: 'financial_management',
        subcategory: 'revenue_analysis',
        templatePattern: 'Show revenue breakdown by course for {timeframe}',
        variables: ['timeframe'],
        description: 'Get revenue breakdown by course',
      },
      {
        templateName: 'Profit Analysis',
        category: 'financial_management',
        subcategory: 'revenue_analysis',
        templatePattern: 'What is the profit margin for {course}?',
        variables: ['course'],
        description: 'Analyze profitability',
      },

      // Operational Insights Templates
      {
        templateName: 'Attendance Rate Analysis',
        category: 'operational_insights',
        subcategory: 'attendance_analysis',
        templatePattern: 'What is the attendance rate for {class_name}?',
        variables: ['class_name'],
        description: 'Get attendance rate for a class',
      },
      {
        templateName: 'Low Attendance Students',
        category: 'operational_insights',
        subcategory: 'attendance_analysis',
        templatePattern: 'Which students have low attendance in {class_name}?',
        variables: ['class_name'],
        description: 'Identify students with low attendance',
      },
      {
        templateName: 'Attendance Performance Correlation',
        category: 'operational_insights',
        subcategory: 'attendance_analysis',
        templatePattern: 'Is there a correlation between attendance and performance in {subject}?',
        variables: ['subject'],
        description: 'Analyze attendance-performance correlation',
      },
      {
        templateName: 'Class Capacity Utilization',
        category: 'operational_insights',
        subcategory: 'resource_utilization',
        templatePattern: 'Show the capacity utilization for all classes',
        variables: [],
        description: 'Get class capacity utilization report',
      },
      {
        templateName: 'Teacher Workload Analysis',
        category: 'operational_insights',
        subcategory: 'resource_utilization',
        templatePattern: 'What is the current workload for {teacher_name}?',
        variables: ['teacher_name'],
        description: 'Analyze teacher workload',
      },
      {
        templateName: 'Subject Distribution',
        category: 'operational_insights',
        subcategory: 'resource_utilization',
        templatePattern: 'How are subjects distributed among teachers?',
        variables: [],
        description: 'Get subject distribution report',
      },
      {
        templateName: 'Timetable Optimization',
        category: 'operational_insights',
        subcategory: 'timetable_optimization',
        templatePattern: 'Suggest an optimal timetable for {class_name}',
        variables: ['class_name'],
        description: 'Get timetable optimization suggestions',
      },
      {
        templateName: 'Exam Schedule Analysis',
        category: 'operational_insights',
        subcategory: 'timetable_optimization',
        templatePattern: 'Analyze the exam schedule for potential conflicts',
        variables: [],
        description: 'Check exam schedule for conflicts',
      },

      // Predictive Analytics Templates
      {
        templateName: 'Student Dropout Risk',
        category: 'predictive_analytics',
        subcategory: 'risk_assessment',
        templatePattern: 'Which students are at risk of dropping out?',
        variables: [],
        description: 'Identify at-risk students',
      },
      {
        templateName: 'Exam Success Prediction',
        category: 'predictive_analytics',
        subcategory: 'performance_prediction',
        templatePattern: 'Predict the success rate for upcoming {subject} exam',
        variables: ['subject'],
        description: 'Predict exam success rate',
      },
      {
        templateName: 'Fee Default Prediction',
        category: 'predictive_analytics',
        subcategory: 'risk_assessment',
        templatePattern: 'Which students might default on fee payments next month?',
        variables: [],
        description: 'Predict fee defaults',
      },
      {
        templateName: 'Enrollment Forecast',
        category: 'predictive_analytics',
        subcategory: 'resource_planning',
        templatePattern: 'Predict enrollment numbers for next {timeframe}',
        variables: ['timeframe'],
        description: 'Forecast future enrollments',
      },
      {
        templateName: 'Performance Improvement Potential',
        category: 'predictive_analytics',
        subcategory: 'performance_prediction',
        templatePattern: 'Which students have the highest potential for improvement?',
        variables: [],
        description: 'Identify students with improvement potential',
      },
      {
        templateName: 'Resource Requirement Planning',
        category: 'predictive_analytics',
        subcategory: 'resource_planning',
        templatePattern: 'What resources will be needed for {timeframe}?',
        variables: ['timeframe'],
        description: 'Plan resource requirements',
      },

      // Administration Templates
      {
        templateName: 'Weekly Performance Report',
        category: 'administration',
        subcategory: 'reporting',
        templatePattern: 'Generate a weekly performance report for {class_name}',
        variables: ['class_name'],
        description: 'Generate weekly performance report',
      },
      {
        templateName: 'Compliance Report',
        category: 'administration',
        subcategory: 'compliance',
        templatePattern: 'Check attendance compliance for all classes',
        variables: [],
        description: 'Generate compliance report',
      },
      {
        templateName: 'Parent Communication Template',
        category: 'administration',
        subcategory: 'communication',
        templatePattern: 'Generate parent notification for {event}',
        variables: ['event'],
        description: 'Generate parent communication',
      },
      {
        templateName: 'Staff Announcement',
        category: 'administration',
        subcategory: 'communication',
        templatePattern: 'Create announcement about {topic}',
        variables: ['topic'],
        description: 'Create staff announcement',
      },
      {
        templateName: 'Student Alert Generation',
        category: 'administration',
        subcategory: 'communication',
        templatePattern: 'Generate alert for students about {issue}',
        variables: ['issue'],
        description: 'Generate student alert',
      },
      {
        templateName: 'Summary Dashboard',
        category: 'administration',
        subcategory: 'reporting',
        templatePattern: 'Show me the dashboard summary for {role}',
        variables: ['role'],
        description: 'Get role-specific dashboard summary',
      },
    ];
  }

  // Method to get templates for auto-generation
  async getTemplateForGeneration(category: string, exampleQuery: string): Promise<string> {
    const templates = await this.getTemplatesByCategory(category);
    
    // Find the most similar template to the example query
    let bestMatch = templates[0];
    let bestScore = 0;

    for (const template of templates) {
      const score = this.calculateSimilarity(exampleQuery, template.templatePattern);
      if (score > bestScore) {
        bestScore = score;
        bestMatch = template;
      }
    }

    return bestMatch?.templatePattern || this.getDefaultTemplate().templatePattern;
  }

  private calculateSimilarity(query: string, template: string): number {
    // Simple similarity calculation - can be enhanced
    const queryWords = new Set(query.toLowerCase().split(' '));
    const templateWords = new Set(template.toLowerCase().split(' '));
    
    const intersection = new Set([...queryWords].filter(x => templateWords.has(x)));
    const union = new Set([...queryWords, ...templateWords]);
    
    return intersection.size / union.size;
  }
}
