import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';

@Entity('ai_patterns')
export class AiPattern {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  patternType: 'query_pattern' | 'intent' | 'entity' | 'template';

  @Column('text')
  pattern: string;

  @Column()
  category: string;

  @Column({ nullable: true })
  subcategory: string;

  @Column('text', { array: true, default: [] })
  keywords: string[];

  @Column({ default: 1 })
  frequency: number;

  @Column('decimal', { precision: 3, scale: 2, default: 0.0 })
  successRate: number;

  @Column('decimal', { precision: 3, scale: 2, default: 0.0 })
  confidenceScore: number;

  @Column({ nullable: true })
  lastUsed: Date;

  @Column({ nullable: true })
  lastSuccess: Date;

  @Column({ default: false })
  autoGenerated: boolean;

  @Column({ default: true })
  isActive: boolean;

  @Column('text', { nullable: true })
  templateExample: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
