import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn } from 'typeorm';

@Entity('ai_prompt_templates')
export class AiPromptTemplate {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  templateName: string;

  @Column()
  category: string;

  @Column({ nullable: true })
  subcategory: string;

  @Column('text')
  templatePattern: string;

  @Column('text', { array: true, default: [] })
  variables: string[];

  @Column('text', { nullable: true })
  description: string;

  @Column({ default: 0 })
  successCount: number;

  @Column({ default: 0 })
  usageCount: number;

  @Column('decimal', { precision: 3, scale: 2, default: 0.0 })
  successRate: number;

  @Column({ nullable: true })
  averageResponseTime: number;

  @Column({ nullable: true })
  lastUsed: Date;

  @Column({ default: true })
  isActive: boolean;

  @Column({ default: false })
  autoGenerated: boolean;

  @Column({ default: 1 })
  version: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
