import React, { useState, useEffect } from 'react';
import {
  Brain, Activity, MessageSquare, ThumbsUp, ThumbsDown,
  Layers, Zap, BarChart3, Clock, RefreshCw, ChevronRight,
  TrendingUp, AlertTriangle, CheckCircle, Star
} from 'lucide-react';
import { cn } from '../ui/utils';
import { apiCall, API_BASE_URL } from '../../config/api.config';

interface LearningMetrics {
  period: string;
  interactions: { total: number; dailyAverage: number };
  feedback: {
    total: number;
    averageRating: number;
    thumbsUp: number;
    thumbsDown: number;
    satisfactionRate: number;
  };
  learning: {
    activePatterns: number;
    activeTemplates: number;
    autoGeneratedTemplates: number;
    patternsDiscovered: number;
    accuracyImprovement: number;
  };
}

interface RecentInteraction {
  id: number;
  question: string;
  responseTime: number;
  createdAt: string;
  feedbackType: string | null;
  rating: number | null;
}

interface InsightData {
  insights: string[];
  recommendations: string[];
  anomalies: any[];
}

interface DashboardData {
  metrics: LearningMetrics;
  insights: InsightData;
  recentInteractions: RecentInteraction[];
}

export function AiDashboard() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'overview' | 'interactions' | 'patterns' | 'templates'>('overview');
  const [refreshing, setRefreshing] = useState(false);

  const fetchDashboard = async () => {
    try {
      setRefreshing(true);
      const data = await apiCall<DashboardData>(`${API_BASE_URL}/api/ai/dashboard`);
      setDashboard(data);
      setError(null);
    } catch (err: any) {
      setError(err.message || 'Failed to load dashboard');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchDashboard();
    const interval = setInterval(fetchDashboard, 60000);
    return () => clearInterval(interval);
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="flex flex-col items-center gap-3">
          <Brain className="w-12 h-12 text-indigo-500 animate-pulse" />
          <p className="text-gray-500">Loading AI Dashboard...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-xl p-6 m-4">
        <div className="flex items-center gap-3">
          <AlertTriangle className="w-6 h-6 text-red-500" />
          <div>
            <h3 className="font-semibold text-red-800">Dashboard Error</h3>
            <p className="text-red-600 text-sm">{error}</p>
          </div>
          <button onClick={fetchDashboard} className="ml-auto px-4 py-2 bg-red-100 text-red-700 rounded-lg hover:bg-red-200 transition-colors">
            Retry
          </button>
        </div>
      </div>
    );
  }

  const m = dashboard?.metrics;
  const ins = dashboard?.insights;

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl">
            <Brain className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">AI Learning Dashboard</h1>
            <p className="text-sm text-gray-500">Monitor AI performance, patterns, and learning progress</p>
          </div>
        </div>
        <button
          onClick={fetchDashboard}
          disabled={refreshing}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-50 text-indigo-700 rounded-lg hover:bg-indigo-100 transition-colors disabled:opacity-50"
        >
          <RefreshCw className={cn('w-4 h-4', refreshing && 'animate-spin')} />
          Refresh
        </button>
      </div>

      {/* Key Metrics Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard
          title="Total Interactions"
          value={m?.interactions.total || 0}
          subtitle={`~${m?.interactions.dailyAverage || 0}/day`}
          icon={MessageSquare}
          color="bg-blue-500"
          bgColor="bg-blue-50"
        />
        <MetricCard
          title="Satisfaction Rate"
          value={`${m?.feedback.satisfactionRate || 0}%`}
          subtitle={`${m?.feedback.thumbsUp || 0} positive`}
          icon={ThumbsUp}
          color="bg-green-500"
          bgColor="bg-green-50"
        />
        <MetricCard
          title="Active Patterns"
          value={m?.learning.activePatterns || 0}
          subtitle={`${m?.learning.patternsDiscovered || 0} new`}
          icon={Layers}
          color="bg-purple-500"
          bgColor="bg-purple-50"
        />
        <MetricCard
          title="Active Templates"
          value={m?.learning.activeTemplates || 0}
          subtitle={`${m?.learning.autoGeneratedTemplates || 0} auto-generated`}
          icon={Zap}
          color="bg-amber-500"
          bgColor="bg-amber-50"
        />
      </div>

      {/* Tabs */}
      <div className="border-b border-gray-200">
        <nav className="flex gap-1">
          {(['overview', 'interactions', 'patterns', 'templates'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={cn(
                'px-4 py-2.5 text-sm font-medium rounded-t-lg transition-colors capitalize',
                activeTab === tab
                  ? 'bg-white border border-b-white border-gray-200 text-indigo-700 -mb-px'
                  : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'
              )}
            >
              {tab}
            </button>
          ))}
        </nav>
      </div>

      {/* Tab Content */}
      {activeTab === 'overview' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* AI Insights */}
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h3 className="font-semibold text-gray-900 flex items-center gap-2 mb-4">
              <TrendingUp className="w-5 h-5 text-indigo-500" />
              Live Insights
            </h3>
            <div className="space-y-3">
              {ins?.insights && ins.insights.length > 0 ? (
                ins.insights.map((insight, idx) => (
                  <div key={idx} className="flex items-start gap-3 p-3 bg-blue-50 rounded-lg">
                    <CheckCircle className="w-4 h-4 text-blue-600 mt-0.5 shrink-0" />
                    <p className="text-sm text-blue-900">{insight}</p>
                  </div>
                ))
              ) : (
                <p className="text-gray-400 text-sm italic">No insights available yet. Interact with the AI to generate data.</p>
              )}
            </div>
          </div>

          {/* Recommendations */}
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h3 className="font-semibold text-gray-900 flex items-center gap-2 mb-4">
              <AlertTriangle className="w-5 h-5 text-amber-500" />
              Recommendations
            </h3>
            <div className="space-y-3">
              {ins?.recommendations && ins.recommendations.length > 0 ? (
                ins.recommendations.map((rec, idx) => (
                  <div key={idx} className="flex items-start gap-3 p-3 bg-amber-50 rounded-lg">
                    <ChevronRight className="w-4 h-4 text-amber-600 mt-0.5 shrink-0" />
                    <p className="text-sm text-amber-900">{rec}</p>
                  </div>
                ))
              ) : (
                <p className="text-gray-400 text-sm italic">No recommendations at this time.</p>
              )}
            </div>
          </div>

          {/* Feedback Breakdown */}
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h3 className="font-semibold text-gray-900 flex items-center gap-2 mb-4">
              <Star className="w-5 h-5 text-yellow-500" />
              Feedback Summary
            </h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="text-center p-4 bg-green-50 rounded-lg">
                <ThumbsUp className="w-6 h-6 text-green-600 mx-auto mb-1" />
                <p className="text-2xl font-bold text-green-700">{m?.feedback.thumbsUp || 0}</p>
                <p className="text-xs text-green-600">Positive</p>
              </div>
              <div className="text-center p-4 bg-red-50 rounded-lg">
                <ThumbsDown className="w-6 h-6 text-red-500 mx-auto mb-1" />
                <p className="text-2xl font-bold text-red-600">{m?.feedback.thumbsDown || 0}</p>
                <p className="text-xs text-red-500">Negative</p>
              </div>
              <div className="text-center p-4 bg-blue-50 rounded-lg col-span-2">
                <p className="text-sm text-blue-600 mb-1">Average Rating</p>
                <div className="flex items-center justify-center gap-1">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <Star
                      key={star}
                      className={cn(
                        'w-5 h-5',
                        star <= Math.round(m?.feedback.averageRating || 0)
                          ? 'text-yellow-400 fill-yellow-400'
                          : 'text-gray-300'
                      )}
                    />
                  ))}
                  <span className="ml-2 text-lg font-semibold text-blue-700">
                    {m?.feedback.averageRating || '—'}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Anomalies */}
          {ins?.anomalies && ins.anomalies.length > 0 && (
            <div className="bg-white rounded-xl border border-red-200 p-5">
              <h3 className="font-semibold text-red-700 flex items-center gap-2 mb-4">
                <AlertTriangle className="w-5 h-5" />
                Anomalies Detected
              </h3>
              <div className="space-y-3">
                {ins.anomalies.map((anomaly, idx) => (
                  <div key={idx} className="p-3 bg-red-50 rounded-lg">
                    <p className="text-sm font-medium text-red-800">{anomaly.message || anomaly.type}</p>
                    {anomaly.action && (
                      <p className="text-xs text-red-600 mt-1">Action: {anomaly.action}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {activeTab === 'interactions' && (
        <div className="bg-white rounded-xl border border-gray-200">
          <div className="p-4 border-b border-gray-200">
            <h3 className="font-semibold text-gray-900 flex items-center gap-2">
              <Activity className="w-5 h-5 text-indigo-500" />
              Recent Interactions
            </h3>
          </div>
          <div className="divide-y divide-gray-100">
            {dashboard?.recentInteractions && dashboard.recentInteractions.length > 0 ? (
              dashboard.recentInteractions.map((interaction) => (
                <div key={interaction.id} className="p-4 hover:bg-gray-50 transition-colors">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <p className="font-medium text-gray-900 text-sm">{interaction.question}</p>
                      <div className="flex items-center gap-4 mt-2">
                        <span className="flex items-center gap-1 text-xs text-gray-500">
                          <Clock className="w-3 h-3" />
                          {interaction.responseTime ? `${interaction.responseTime}ms` : '—'}
                        </span>
                        <span className="text-xs text-gray-400">
                          {new Date(interaction.createdAt).toLocaleString()}
                        </span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 ml-4">
                      {interaction.feedbackType === 'thumbs_up' && (
                        <ThumbsUp className="w-4 h-4 text-green-500" />
                      )}
                      {interaction.feedbackType === 'thumbs_down' && (
                        <ThumbsDown className="w-4 h-4 text-red-500" />
                      )}
                      {interaction.rating && (
                        <span className="flex items-center gap-1 text-xs bg-yellow-100 text-yellow-700 px-2 py-0.5 rounded-full">
                          <Star className="w-3 h-3 fill-yellow-500 text-yellow-500" />
                          {interaction.rating}
                        </span>
                      )}
                      {!interaction.feedbackType && !interaction.rating && (
                        <span className="text-xs text-gray-400 italic">No feedback</span>
                      )}
                    </div>
                  </div>
                </div>
              ))
            ) : (
              <div className="p-8 text-center text-gray-400">
                <MessageSquare className="w-8 h-8 mx-auto mb-2 opacity-50" />
                <p>No interactions yet</p>
              </div>
            )}
          </div>
        </div>
      )}

      {activeTab === 'patterns' && <PatternsTab />}
      {activeTab === 'templates' && <TemplatesTab />}
    </div>
  );
}

function MetricCard({ title, value, subtitle, icon: Icon, color, bgColor }: {
  title: string;
  value: string | number;
  subtitle: string;
  icon: React.ElementType;
  color: string;
  bgColor: string;
}) {
  return (
    <div className={cn('rounded-xl border border-gray-200 p-5', bgColor)}>
      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm text-gray-600">{title}</p>
          <p className="text-3xl font-bold text-gray-900 mt-1">{value}</p>
          <p className="text-xs text-gray-500 mt-1">{subtitle}</p>
        </div>
        <div className={cn('p-3 rounded-xl', color)}>
          <Icon className="w-6 h-6 text-white" />
        </div>
      </div>
    </div>
  );
}

function PatternsTab() {
  const [patterns, setPatterns] = useState<{ patterns: any[]; categories: any[]; total: number } | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    apiCall<any>(`${API_BASE_URL}/api/ai/patterns`)
      .then(setPatterns)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="text-center py-8 text-gray-400">Loading patterns...</div>;

  return (
    <div className="space-y-4">
      {/* Category chips */}
      {patterns?.categories && patterns.categories.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {patterns.categories.map((cat: any) => (
            <span key={cat.name} className="px-3 py-1.5 bg-indigo-50 text-indigo-700 rounded-full text-sm font-medium">
              {cat.name} ({cat.count})
            </span>
          ))}
        </div>
      )}

      <div className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-100">
        {patterns?.patterns && patterns.patterns.length > 0 ? (
          patterns.patterns.slice(0, 20).map((pattern: any, idx: number) => (
            <div key={pattern.id || idx} className="p-4 flex items-center justify-between">
              <div>
                <p className="font-medium text-gray-900 text-sm">{pattern.pattern}</p>
                <div className="flex items-center gap-3 mt-1">
                  <span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded">{pattern.patternType}</span>
                  <span className="text-xs text-gray-500">Category: {pattern.category}</span>
                  {pattern.autoGenerated && <span className="text-xs bg-purple-100 text-purple-600 px-2 py-0.5 rounded">Auto</span>}
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm font-semibold text-gray-700">{pattern.frequency}x</p>
                <p className="text-xs text-gray-400">used</p>
              </div>
            </div>
          ))
        ) : (
          <div className="p-8 text-center text-gray-400">
            <Layers className="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p>No patterns discovered yet</p>
            <p className="text-xs mt-1">Patterns are automatically learned from user interactions</p>
          </div>
        )}
      </div>
    </div>
  );
}

function TemplatesTab() {
  const [data, setData] = useState<{ templates: any[]; categories: any[] } | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);

  useEffect(() => {
    const url = selectedCategory
      ? `${API_BASE_URL}/api/ai/templates?category=${selectedCategory}`
      : `${API_BASE_URL}/api/ai/templates`;
    apiCall<any>(url)
      .then(setData)
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [selectedCategory]);

  if (loading) return <div className="text-center py-8 text-gray-400">Loading templates...</div>;

  return (
    <div className="space-y-4">
      {/* Category filter */}
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => setSelectedCategory(null)}
          className={cn(
            'px-3 py-1.5 rounded-full text-sm font-medium transition-colors',
            !selectedCategory ? 'bg-indigo-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
          )}
        >
          All
        </button>
        {data?.categories?.map((cat: any) => (
          <button
            key={cat.name}
            onClick={() => setSelectedCategory(cat.name)}
            className={cn(
              'px-3 py-1.5 rounded-full text-sm font-medium transition-colors',
              selectedCategory === cat.name ? 'bg-indigo-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            )}
          >
            {cat.name.replace(/_/g, ' ')} ({cat.count})
          </button>
        ))}
      </div>

      <div className="bg-white rounded-xl border border-gray-200 divide-y divide-gray-100">
        {data?.templates && data.templates.length > 0 ? (
          data.templates.map((tpl: any) => (
            <div key={tpl.id} className="p-4">
              <div className="flex items-start justify-between">
                <div>
                  <p className="font-medium text-gray-900 text-sm">{tpl.templateName}</p>
                  <p className="text-xs text-gray-500 mt-1">{tpl.description}</p>
                  <p className="text-xs text-gray-400 mt-1 font-mono bg-gray-50 px-2 py-1 rounded inline-block">
                    {tpl.templatePattern}
                  </p>
                </div>
                <div className="text-right shrink-0 ml-4">
                  <div className="flex items-center gap-1 text-xs text-gray-500">
                    <BarChart3 className="w-3 h-3" />
                    {tpl.usageCount || 0} uses
                  </div>
                  <div className="text-xs text-green-600 mt-1">
                    {((tpl.successRate || 0) * 100).toFixed(0)}% success
                  </div>
                  {tpl.autoGenerated && (
                    <span className="text-xs bg-purple-100 text-purple-600 px-2 py-0.5 rounded mt-1 inline-block">Auto</span>
                  )}
                </div>
              </div>
            </div>
          ))
        ) : (
          <div className="p-8 text-center text-gray-400">
            <Zap className="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p>No templates found</p>
          </div>
        )}
      </div>
    </div>
  );
}
